#!/bin/bash

SOCKET=/var/tmp/radio.sock
declare -A STATIONS=(
[mute]='tail -f /dev/null'
[KEXP]='mpg321 http://50.31.180.202:80/'
[SomaFM (Groove Salad)]='mpg321 http://ice2.somafm.com/groovesalad-128-mp3'
[SomaFM (Cliqhop)]='mpg321 http://ice2.somafm.com/cliqhop-128-mp3'
[UH radio]='mpg321 http://online.uhradio.com.ua:8001/efir'
[San Diego\'s Jazz]='mpg321 http://ksds-ice.streamguys1.com/ksds.mp3'
[Virgin RADIO]='mpg321 http://vr-live-mp3-128.scdn.arkena.com/virginradio.mp3'
);
DIRECTORY=$(dirname "$0")
echo $DIRECTORY

handle_request() {
    method=$1
    uri=$2
    uri=${uri:1:${#uri}-1}
    echo -e 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n'
    if [ -z $uri ]; then
	HOME_PAGE=`cat "$DIRECTORY/index.html"`
	echo "$HOME_PAGE"
    elif [[ $uri == "list" ]]; then
	echo -n "{\"stations\":["
	for station in "${!STATIONS[@]}"; do
	    echo "\"$station\""
	done | sort | tr "\\n" "," | sed 's/,$//'
	echo -n "]}"
    else
	echo "{}"
        CMD=`echo $uri | sed 's/\%20\|\+/ /g'`
	#echo $uri | sed 's/\%20\|\+/ /g' | nc -U $SOCKET
	echo $CMD | nc -U $SOCKET
    fi
}

(
    while true; do
	PIPE=`mktemp -u --suffix=radio`
	mkfifo $PIPE
	cat $PIPE | stdbuf -oL nc -l 8085 > >(
	    read line; handle_request $line > $PIPE
	)
	rm -f $PIPE
    done
) &

WEBSERVER_PID=$!

(
    INDEX=KEXP

    while true; do
	PLAY_CMD=${STATIONS["$INDEX"]}
	eval "$PLAY_CMD || [[ $? -ne 137 ]] && echo noop | nc -U $SOCKET" &

	SUBSHELL_PID=$!

	while CMD=$(nc -Ul $SOCKET) && [[ -z "$CMD" ]]; do :
	done
	echo Command: $CMD
	pkill --signal KILL -P $SUBSHELL_PID
	case "$CMD" in
    	    exit)
		break
        	;;
	    play/?*)
		INDEX=${CMD:5:${#CMD}-1}
		;;
	esac
	done
) &

trap "echo exit | nc -U $SOCKET" SIGINT SIGTERM EXIT

wait $!

kill -- -$(ps -o pgid= $WEBSERVER_PID | grep -o [0-9]*)
